### ISSUE TITLE
processing popup after failure

### ISSUE THREAD

**Issue by stdweird** [UtrechtUniversity/yoda-portal-research#12]
using @lwesterhof commit
https://github.com/UtrechtUniversity/yoda-portal-research/commit/6e66c377a8c96a3d6f188cd0920a7e7c78803da5

gives gives a nice warning message, but still has a "Porcessing" popup

following screenshot
![yoda-research-processing](https://user-images.githubusercontent.com/1517606/48698117-933c2d00-ebe6-11e8-9df7-2f01ab0f4fbe.png)

**Comment by lwesterhof** [comment]
Thanks!
